FROM jeanblanchard/busybox-java:8
MAINTAINER rolandkrueger
EXPOSE 8080
CMD java -Xmx500m -Xms250m -jar /data/vaadin-by-example-demo-1.1.war
ADD build/vaadin-by-example-demo-1.1.war /data/vaadin-by-example-demo-1.1.war