// Generated by delombok at Sun Apr 13 12:08:23 CEST 2014
package de.oio.vaadin.demo;

public class DemoInfo {
  private String codeHostingURI;
  private String blogPostURI;
  private String blogPostTitle;
  private String shortDescriptionKey;
  private String demoHeadlineKey;

  public DemoInfo() {
  }

  public String getCodeHostingURI() {
    return this.codeHostingURI;
  }

  public String getBlogPostURI() {
    return this.blogPostURI;
  }

  public String getBlogPostTitle() {
    return this.blogPostTitle;
  }

  public String getShortDescriptionKey() {
    return this.shortDescriptionKey;
  }

  public String getDemoHeadlineKey() {
    return this.demoHeadlineKey;
  }

  public void setCodeHostingURI(final String codeHostingURI) {
    this.codeHostingURI = codeHostingURI;
  }

  public void setBlogPostURI(final String blogPostURI) {
    this.blogPostURI = blogPostURI;
  }

  public void setBlogPostTitle(final String blogPostTitle) {
    this.blogPostTitle = blogPostTitle;
  }

  public void setShortDescriptionKey(final String shortDescriptionKey) {
    this.shortDescriptionKey = shortDescriptionKey;
  }

  public void setDemoHeadlineKey(final String demoHeadlineKey) {
    this.demoHeadlineKey = demoHeadlineKey;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object o) {
    if (o == this)
      return true;
    if (!(o instanceof DemoInfo))
      return false;
    final DemoInfo other = (DemoInfo) o;
    if (!other.canEqual((java.lang.Object) this))
      return false;
    final java.lang.Object this$codeHostingURI = this.getCodeHostingURI();
    final java.lang.Object other$codeHostingURI = other.getCodeHostingURI();
    if (this$codeHostingURI == null ? other$codeHostingURI != null : !this$codeHostingURI.equals(other$codeHostingURI))
      return false;
    final java.lang.Object this$blogPostURI = this.getBlogPostURI();
    final java.lang.Object other$blogPostURI = other.getBlogPostURI();
    if (this$blogPostURI == null ? other$blogPostURI != null : !this$blogPostURI.equals(other$blogPostURI))
      return false;
    final java.lang.Object this$blogPostTitle = this.getBlogPostTitle();
    final java.lang.Object other$blogPostTitle = other.getBlogPostTitle();
    if (this$blogPostTitle == null ? other$blogPostTitle != null : !this$blogPostTitle.equals(other$blogPostTitle))
      return false;
    final java.lang.Object this$shortDescriptionKey = this.getShortDescriptionKey();
    final java.lang.Object other$shortDescriptionKey = other.getShortDescriptionKey();
    if (this$shortDescriptionKey == null ? other$shortDescriptionKey != null : !this$shortDescriptionKey
        .equals(other$shortDescriptionKey))
      return false;
    final java.lang.Object this$demoHeadlineKey = this.getDemoHeadlineKey();
    final java.lang.Object other$demoHeadlineKey = other.getDemoHeadlineKey();
    if (this$demoHeadlineKey == null ? other$demoHeadlineKey != null : !this$demoHeadlineKey
        .equals(other$demoHeadlineKey))
      return false;
    return true;
  }

  public boolean canEqual(final java.lang.Object other) {
    return other instanceof DemoInfo;
  }

  @java.lang.Override
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $codeHostingURI = this.getCodeHostingURI();
    result = result * PRIME + ($codeHostingURI == null ? 0 : $codeHostingURI.hashCode());
    final java.lang.Object $blogPostURI = this.getBlogPostURI();
    result = result * PRIME + ($blogPostURI == null ? 0 : $blogPostURI.hashCode());
    final java.lang.Object $blogPostTitle = this.getBlogPostTitle();
    result = result * PRIME + ($blogPostTitle == null ? 0 : $blogPostTitle.hashCode());
    final java.lang.Object $shortDescriptionKey = this.getShortDescriptionKey();
    result = result * PRIME + ($shortDescriptionKey == null ? 0 : $shortDescriptionKey.hashCode());
    final java.lang.Object $demoHeadlineKey = this.getDemoHeadlineKey();
    result = result * PRIME + ($demoHeadlineKey == null ? 0 : $demoHeadlineKey.hashCode());
    return result;
  }

  @java.lang.Override
  public java.lang.String toString() {
    return "DemoInfo(codeHostingURI=" + this.getCodeHostingURI() + ", blogPostURI=" + this.getBlogPostURI()
        + ", blogPostTitle=" + this.getBlogPostTitle() + ", shortDescriptionKey=" + this.getShortDescriptionKey()
        + ", demoHeadlineKey=" + this.getDemoHeadlineKey() + ")";
  }
}